apiVersion: apps/v1
kind: Deployment
metadata:
  name: insuranceapp-project
  labels:
    app: insuranceapp-w1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: insuranceapp-w1
  template:
    metadata:
      labels:
        app: insuranceapp-w1
    spec:
      containers:
      - name: bankapp-w1-container
        image: venkt06/insuranceapp-w1-app:tagversion
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: insuranceapp-w1-np-service
  labels:
    app: insuranceapp-w1
spec:
  selector:
    app: insuranceapp-w1
  type: NodePort
  ports:
  - nodePort: 31234    
    port: 8081
    targetPort: 8081